const colors = {
  light: {
    text: "#0C1526",
    tint: "#1F4E79",
    background: "#F8FAFC",
    foreground: "#0C1526",
    card: "#FFFFFF",
    cardForeground: "#0C1526",
    primary: "#1F4E79",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF4FB",
    secondaryForeground: "#1F4E79",
    muted: "#EEF4FB",
    mutedForeground: "#64748B",
    accent: "#3B82F6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDE5EE",
    input: "#E2E8F0",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
  },
  dark: {
    text: "#F8FAFC",
    tint: "#60A5FA",
    background: "#0C1526",
    foreground: "#F8FAFC",
    card: "#172035",
    cardForeground: "#F8FAFC",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3050",
    secondaryForeground: "#F8FAFC",
    muted: "#1E3050",
    mutedForeground: "#94A3B8",
    accent: "#60A5FA",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D4060",
    input: "#243452",
    success: "#4ADE80",
    successForeground: "#0C1526",
    warning: "#FCD34D",
    warningForeground: "#0C1526",
    info: "#60A5FA",
    infoForeground: "#FFFFFF",
  },
  radius: 8,
};

export default colors;
