uploads = []

[[generated]]
id = "lhWS9lQPBDyqqODx3nyWY"
uri = "file://artifacts/mbs-crm-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "o3z6dDo2HWXmopqbzLI3T"
uri = "file://MBS_CRM_Audit_Report.pdf"
type = "pdf"
title = "MBS CRM — Project Audit Report"

[[outputs]]
id = "kcG-Kb5bsp3oUNmk1eRwd"
uri = "file://mbs-crm-timeline.pdf"
type = "pdf"
title = "MBS CRM — Weekly Timeline"
